language: cpp
sudo: true
compiler:
    - g++
before_install:
    - wget https://github.com/google/leveldb
    - cd leveldb
    - make
    - sudo mv out-shared/libleveldb.* /usr/local/lib
    - cd ..
script:
    - cmake && make
