language: cpp
sudo: true
dist: trusty
compiler:
  - g++

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsnappy-dev
  - git submodule update --init --recursive

install:
  - cmake SW

script:  
  - make
